### ISSUE TITLE
Can you add an example how to use it in tableviewcell?

### ISSUE THREAD

**Issue by ac1dpax** [kbelter/BubblePictures#15]
Please can you add an example how to use it correctly in tableviewcell, also how to configure names and titles from array? I have successfully added bubbles in cells, but unable to configure names and images. Not a lot experience in swift, thank you!

**Comment by glassipbel** [comment]
Hi there!

Sure! The good news is that, it's super easy to implement :)
The steps are the following.

First of all, you should add a UICollectionView inside your UITableViewCell.
Once you do that, you should have a reference to that collectionview.

If you do that by code probably you will have a variable in your tableviewcell such as var collectionview = UICollectionView() or if you did that using storyboards or xib files you should have the same but as an IBOutlet.

In both cases you have a reference to that collectionview.

The second step is to have a reference in the the same tableviewcell to bubblepictures class.

So you will need to import BubblePictures in your tableviewcell class.
Second declare a private var bubblePictures: BubblePictures? in your tableviewcell as well.

Then third step, in your cellForRow method that you are overriding you need to configure and assign the bubblePictures reference that you declare before by doing something like this:

//The config files are the images that you will be rendering
let configFiles: [BPCellConfigFile] = yourArray.map {
            return BPCellConfigFile(imageType: .URL($0.urlOfTheImage), title: $0.nameOfTheBubble)
}
let layoutConfigurator = BPLayoutConfigurator(
            backgroundColorForTruncatedBubble: THECOLORTHATYOUWANTFORTRUNCATED,
            fontForBubbleTitles: YOURFONT,
            colorForBubbleBorders: COLORFORBORDERS,
            colorForBubbleTitles: COLORFORTITLES,
            maxNumberOfBubbles: THEMAXAMOUNTOFBUBBLES,
            numberForTruncatedCell: THENUMBERTHATYOUWANTTOSHOWINTHETRUNCATION,
            alignment: THE ALIGNMENTOFTHE BUBBLES
        )
        
        bubblePictures = BubblePictures(collectionView: collectionView, configFiles: configFiles, layoutConfigurator: layoutConfigurator)
        collectionView.reloadData()

Additionaly if you want to do something when they tap a bubble, you should add one more line like:
bubblePictures.delegate = self

and then extend your tableviewcell with BubblePicturesDelegate and implement the 2 methods that are available.

**Comment by glassipbel** [comment]
i also forgot to mention that you need to put the constraints to the collectionview so the bubblepictures knows where to be rendered.
