### ISSUE TITLE
Objective C

### ISSUE THREAD

**Issue by ErAshu** [kbelter/BubblePictures#2]
How can we use this in objective C ?

**Comment by kbelter** [comment]
Hi ErAshu!
Yes you would need to use a Bridge Header in order to use it, but in theory there shouldn't be any problem.
Let me know if that worked well :)

Regards, Kevin Bel.

**Comment by inPhilly** [comment]
I can't find a way to make this work in an Objective-C project. Can you include a few lines of code in Objective-C as an example?

**Comment by kbelter** [comment]
@inPhilly Hi!
i tried to use the library in Objc but i'm using structs and enums and another data structures in swift that are not available at Objective C because their are using associated values.
So i was wrong, you cannot use this library in Objective C, this library is only for Swift usage.
