### ISSUE TITLE
Swift4 support

### ISSUE THREAD

**Issue by day1-suraj** [kbelter/BubblePictures#3]
The projects needs to be updated for swift 4 support. I've attached snapshot of the error I'm receiving
<img width="1407" alt="screen shot 2017-09-30 at 12 35 39 am" src="https://user-images.githubusercontent.com/32399827/31031798-614d22a6-a577-11e7-9a28-ee9980846ea1.png">

**Comment by kbelter** [comment]
Absolutely!
Thank you for the support!
I will Update the project in the next hours.
Hopefully i will have it by today at night or tomorrow!

**Comment by kbelter** [comment]
@day1-suraj Done!
Bubble Pictures is now available for Swift 4.0.
The version supporting Swift 4.0 is the 1.1.0.
So in your Podfile remember to change that (if you are pointing to a lower version or an specific one.)
Then run pod update as always.
Thanks for the reminder and have a great day!
