### ISSUE TITLE
Update to the latest version of SDWebimage 4.2.2

### ISSUE THREAD

**Issue by lordjjl** [kbelter/BubblePictures#4]
Hey there! Is there any chance that you'll be able to update the podspec to use the latest version of SDWebImage? I need features of the latest SDWebImage but BubblePictures is preventing me from updating.

Thanks!

**Comment by kbelter** [comment]
@lordjjl Thank you for the reminder!
That's it, its updated and i removed the version so this wont happen in the future.
Thank you for using Bubble Pictures!
Regards, Kevin.
