### ISSUE TITLE
Layout broken for small height

### ISSUE THREAD

**Issue by Drusy** [kbelter/BubblePictures#5]
The result is not as expected if you set the height constraint of the collectionview of 40 in your example and also `maxNumberOfBubbles = 2`.
Any clue ?

**Comment by kbelter** [comment]
You are right! i will fix that ASAP give me a couple of minutes :P

**Comment by Drusy** [comment]
Settings `distanceInterBubbles` seems to fix the problem if it can help :)

**Comment by kbelter** [comment]
@Drusy Done!
Please update to version 1.1.3 and the problem will be solved :P 
Thank you for reporting the issue!
By the way, great name! haha..
