### ISSUE TITLE
Cannot invoke initializer for type 'Range<_>' with an argument list of type '(Range<String.Index>)'

### ISSUE THREAD

**Issue by killvak** [kbelter/BubblePictures#7]
in ->  StringExtensions.swift  file there's an error on line 32  which is :  
Cannot invoke initializer for type 'Range<_>' with an argument list of type '(Range<String.Index>)'

i fixed it by replacing the line with 
        let range2 : Range = start ..< end
        return String(self[range2])

**Comment by kbelter** [comment]
Hi there!
1. What version of bubble pictures do you have?

2.Have you tried updating it?

3. Also what version of swift are you running in your project?

4. And in what version of swift is configured for BubblePictures?

Thanks.

**Comment by kbelter** [comment]
@killvak Do you manage to solve the issue? 
Please let me know if not this issue will be closed, however you can reopen it if the problem persists.
Regards, Kevin.

**Comment by kbelter** [comment]
@killvak Since you didn't replied i believe this issue is gone.
However if the problem persist, please re open this issue with more details so i can help you with it.
Regards, Kevin.

**Comment by killvak** [comment]
the same problem happened again, i'm using swift 4 and  BubblePictures version is (1.1.6)

**Comment by killvak** [comment]
<img width="1437" alt="screen shot 2018-09-24 at 11 54 21 am" src="https://user-images.githubusercontent.com/24807988/45946243-a40a6100-bff0-11e8-814e-b30ffa65959d.png">

**Comment by kbelter** [comment]
Hi there
I’m working on that, i’m trying to publish the fix however i’m having a couple of issues when publishing.
Hope to have It done by EOD
